name: yummy
description: Your recipes here.

publish_to: "none"

version: 1.6.3+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  delayed_display: ^1.1.0
  syncfusion_flutter_charts: ^19.3.54
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.2
  firebase_storage: ^8.0.2
  firebase_messaging: ^9.1.1
  provider: ^5.0.0
  alphabet_list_scroll_view: ^2.0.0
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  uuid: ^3.0.3
  google_sign_in: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: ^0.9.2

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "dev_assets/yummy.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "dev_assets/yummy-adaptive.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    # - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Anurati
      fonts:
        - asset: assets/fonts/Anurati-Regular.otf
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf
    - family: RemottelyIcons
      fonts:
        - asset: assets/fonts/RemottelyIcons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
        - asset: assets/fonts/MyFlutterApp2.ttf
    - family: Astronaut_PersonalUse
      fonts:
        - asset: assets/fonts/Astronaut_PersonalUse.otf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay_VariableFont_wght.ttf
