name: yummy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.2+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  ################################################ old
  # carousel_pro: ^1.0.0
  # sliding_up_panel: ^1.0.2
  # gallery_saver: ^2.0.1
  # cpf_cnpj_validator: ^1.0.5
  # flushbar: ^1.10.4 #removed
  ################################################ New null-safety
  flutter_launcher_icons: ^0.8.1
  reorderable_carousel: ^0.2.0 #ok
  # flutter_card_swipper: ^0.4.0
  # fl_chart: ^0.40.2
  delayed_display: ^1.1.0
  syncfusion_flutter_charts: ^19.3.54
  sliding_sheet: ^0.5.0 #ok
  # gallery_saver_safety: ^1.0.7
  validatorless: ^1.0.0 #ok
  another_flushbar: ^1.10.17 #ok
  ################################################ old -> null-safety
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.4
  cloud_functions: ^1.0.3
  firebase_auth: ^1.0.2
  firebase_storage: ^8.0.2
  firebase_messaging: ^9.1.1
  # cloud_firestore: ^1.0.4
  # cloud_functions: ^1.0.3
  # firebase_auth: ^1.0.2
  # firebase_storage: ^8.0.2
  # firebase_messaging: ^6.0.16
  provider: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  transparent_image: ^2.0.0
  alphabet_list_scroll_view: ^2.0.0
  faker: ^2.0.0-rc.2
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  uuid: ^3.0.3
  dio: ^4.0.0
  brasil_fields: ^1.1.1
  geolocator: ^7.0.1
  screenshot: ^1.0.0-nullsafety.1
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.0.3
  # map_launcher: ^2.0.0
  flip_card: ^0.5.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  credit_card_type_detector: ^2.0.0-nullsafety.0
  keyboard_actions: ^3.4.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.21.0+1
  http: ^0.13.0 #^0.13.0 
  ################################################ Future null-safety
  flutter_local_notifications: ^5.0.0+1
  # delayed_display: ^2.0.0
  insta_public_api: ^0.1.1 #^0.1.1
  # clipboard 0.1.3
  # flutter_instagram_stories 1.0.0
  # instagram_share: ^0.2.0 #remove?
  social_share: ^2.1.1
  google_sign_in: ^5.0.1
  # screenshot: ^0.3.0
  #
  #
  ################################################ Future
  flutter_gifimage: ^1.0.1
  # stories_for_flutter: ^0.1.8
  # flutter_social_content_share: ^0.0.4
  # social_media_widgets 1.0.0+2
  # flutter_instagram_image_picker: ^1.1.0+3
  # flutter_downloader: ^1.5.2
  # flutter_insta: ^0.1.4
  # instagram_mention: ^0.0.1+1
  # insta_html_parser: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Anurati
      fonts:
        - asset: assets/fonts/Anurati-Regular.otf
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf
    - family: RemottelyIcons
      fonts:
        - asset: assets/fonts/RemottelyIcons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
        - asset: assets/fonts/MyFlutterApp2.ttf
    - family: Astronaut_PersonalUse
      fonts:
        - asset: assets/fonts/Astronaut_PersonalUse.otf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay_VariableFont_wght.ttf
        
flutter_icons:    
  android: "launcher_icon"    
  ios: true    
  image_path: "assets/icon/icon.png" 
